### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by jcarr-awake** [aristanetworks/eos-external-tools#108]
I can't see any instructions for building the project, and the exact barney commands to run might not be obvious without full experience (such as when one is looking to use eext for the first time).

Docker build/run instructions would also be helpful, as a naive `docker build .` and `docker run <sha256> -t /bin/bash` froze for me, where sha256 is the name of the docker build result.

**Comment by manith-arista** [comment]
We have updated the docker workflow to automate the build steps, so that any changes made to the tool are bundled through eext-bus.
