### ISSUE TITLE
authenticate bashbrew with github

### ISSUE THREAD

**Issue by shyammohan-arista** [aristanetworks/eos-external-tools#30]
authenticate bashbrew with github so that we have the option to make the repo private/internal in github in the future.
This way the bashbrew can build the docker image and push to library without making the eos-external-tools repo public.

**Comment by shyammohan-arista** [comment]
https://gerrit.corp.arista.io/c/docker-library/+/249476/comments/27fabdd3_48ba6211

**Comment by aajith-arista** [comment]
distributed with barney and not docker-library now.
So closing this
